### ISSUE TITLE
Long compilation time

### ISSUE THREAD

**Issue by T-Rex96** [PatWie/CppNumericalSolvers#106]
When including this library into my C++ project, the compilation increases significantly by almost an order of magnitude. Is there some way to reduce this time, perhaps by precompiling the library?

**Comment by T-Rex96** [comment]
The thing is, I already use Eigen in my project, so that can't be the bottleneck here. Seems like it's the templates then

**Comment by PatWie** [comment]
I admit the heavily usage of templates in this library, which is albeit on purpose.
