### ISSUE TITLE
Optimization report?

### ISSUE THREAD

**Issue by Daiver** [PatWie/CppNumericalSolvers#109]
Is it possible to obtain information about number of passed iterations, number of function/gradient calls, etc after optimization? 
I only found commented lines "std::cout << "iter: ""

**Comment by PatWie** [comment]
This is what the [Criterial](https://github.com/PatWie/CppNumericalSolvers/blob/97e97c55d5a514c102f6aa746e4f3719d9eefe4c/include/cppoptlib/meta.h) object is for. See the example

https://github.com/PatWie/CppNumericalSolvers/blob/97e97c55d5a514c102f6aa746e4f3719d9eefe4c/src/examples/simple_withoptions.cpp#L42-L49
