### ISSUE TITLE
Share computation between value() and gradient()

### ISSUE THREAD

**Issue by bing-jian** [PatWie/CppNumericalSolvers#115]
Hi Patrick,

First thanks a lot for creating this library.  I am switching from vnl to Eigen and looking for a nonlinear optimization library based on Eigen that can replace the 
https://public.kitware.com/vxl/doc/release/core/vnl/html/classvnl__cost__function.html
.  The cppoptlib::Problem class seems can fill this role.  However, I have a question when trying to migrate some functions from vnl_cost_function to cppoptlib::Problem.   For many functions, the evaluation and calculating derivatives actually share some common computation.  I am wondering if there is a way to share computation between value() and gradient().  For example if it is always the case that the value() function is called before gradient() or the other way around,  we can save some intermediate results in the function being called first and then use them later in another function.  This could save some unnecessary computational cost especially when both value() and gradient() are computationally heavy if running independently.   

I hope the problem described above is clear and thanks for your attention!

--
Bing

**Comment by PatWie** [comment]
Some solvers currently do not need both information at the same time, eg. BFGS. But I agree, that a combining the computation will help. The first idea would to extend the “problem” interface by adding the method “value_gradient” which shares the computation. This way the solvers can decide if they need both information and the default can just call the “value” and “gradient” method without breaking changes.

**Comment by dandoh** [comment]
@bing-jian @PatWie any plan to implement the shared computation yet?

**Comment by PatWie** [comment]
v2 has now an eval function to compute the entire state

https://github.com/PatWie/CppNumericalSolvers/blob/a8e8d7f33fcc531dc82c27a0c2b5342961a6de57/include/cppoptlib/function.h#L75-L88
