### ISSUE TITLE
The way to calculate a finite Hessian

### ISSUE THREAD

**Issue by chobby** [PatWie/CppNumericalSolvers#120]
Hi,

I'm very interested in the way how to get the finite Hessian.
And I found the formula in the source code as below
![ql_33f872e3aca0ced980df364cbf8ca362_l3](https://user-images.githubusercontent.com/5764581/83397143-13785b00-a438-11ea-9189-5be14ebe6afd.png)
I would appreciate if you give me some information about the formula.

**Comment by PatWie** [comment]
Please have a look at finite differences. This is no magic here. The `2`, `1` referring to `eps` added/subtracted to coordinates.
