### ISSUE TITLE
LbfgsbSolver<TProblem>::SubspaceMinimization   for first iteration     

### ISSUE THREAD

**Issue by jake-camero** [PatWie/CppNumericalSolvers#122]
This issue refers to version 1.0.0 (last stable version), though it might occur also in later versions (I haven't checked that). This is the issue:

The example nonnegls.cpp crashes in the very first call to LbfgsbSolver<TProblem>::SubspaceMinimization. 

I think the reason is that for the first iteration matrix W still has zero columns (as there are no previous steps yet). I think that the problem will be fixed if, for the first iteration,

du(i) = -g(i)     , if bounds are not active at i, or they are active but g(i) points outward
du(i) = 0,           otherwise   

Obviously, if at every position bounds are active with the gradient pointing inward, an optimum has been reached

**Comment by PatWie** [comment]
I saw this issue with newer versions of EIGEN. I will take a look.

**Comment by PatWie** [comment]
Should be fixed in 2649780e8f136381dd7f0dc406482a4f16b54b18
