### ISSUE TITLE
Eigen::indexing::all not found

### ISSUE THREAD

**Issue by copyme** [PatWie/CppNumericalSolvers#125]
Hello!

I tried to use the code but it seems like there is an issue with Eigen

```
include/cppoptlib/solver/lbfgsb.h:270:41: error: ‘Eigen::indexing’ has not been declared
         W_(free_variables_index, Eigen::indexing::all).transpose();
```

I am compiling against Eigen 3.3.7. Do I need any other specific version?

**Comment by sschnug** [comment]
Without checking, i would say that most advanced indexing routines in Eigen are only available in master.

See [docs](https://eigen.tuxfamily.org/dox-devel/group__TutorialSlicingIndexing.html):

> This page presents the numerous possibilities offered by operator() to index sub-set of rows and columns. This API has been introduced in Eigen 3.4. It supports all the feature proposed by the block API , and much more. In particular, it supports slicing that consists in taking a set of rows, columns, or elements, uniformly spaced within a matrix or indexed from an array of indices.

There is no 3.4 release yet.

**Comment by PatWie** [comment]
Closing this issue as the dependency is specified for bazel.
