### ISSUE TITLE
Trace (similar to R trace=(1..6)) after each iteration

### ISSUE THREAD

**Issue by divaykin** [PatWie/CppNumericalSolvers#13]
Would be great to print some info after each iteration (norm, objective, etc) like R can do. Or maybe provide an iteration callback so user can assess Solver state.

**Comment by PatWie** [comment]
It's already thee. Just uncomment:
https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/solver/gradientdescentsolver.h#L31
https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/solver/lbfgssolver.h#L103
...

**Comment by PatWie** [comment]
I will reopen this issue, if this feature is requested again.
