### ISSUE TITLE
Including this implementation in another package with proper credits to the authors

### ISSUE THREAD

**Issue by Shihao-Yang** [PatWie/CppNumericalSolvers#132]
We are writing another c++ package with interface in R (https://github.com/wongswk/magi) that uses your implementation as a dependency. We plan to submit the package to CRAN (https://cran.r-project.org/) and want to make sure authors here are properly credited despite the MIT license. 

If you agree, we will list the main author Patrick Wieschollek as a contributor for our R package (https://github.com/wongswk/magi/tree/master/rmagi). Please let us know.

**Comment by PatWie** [comment]
Sure, I agree.
