### ISSUE TITLE
Enable changing line search strategies?

### ISSUE THREAD

**Issue by unclejimbo** [PatWie/CppNumericalSolvers#134]
Hi, thanks for your great work.

Currently the line search functions are hard-coded into the solvers. But sometimes we want to use the base solver for the search direction but use a different line search algorithm based on the specific problem at hand. Do you ever consider adding an option to let the user change line search strategies? Maybe as a template parameter to the Solver class.

**Comment by PatWie** [comment]
The line-search methods have been carefully chosen to make the benchmark functions pass. I am happy to take a PR that exposes the line-search method (ideally as a function within a solver-struct) to the solver-algorithm.
