### ISSUE TITLE
document

### ISSUE THREAD

**Issue by xiaoxiaojiea** [PatWie/CppNumericalSolvers#147]
hello, i find this is a excellent repository , but i want konw is there have any document or others detial about this reposity?

**Comment by PatWie** [comment]
Thank you for your kind words and interest in this repository!

CppNumericalSolvers is a collection of generic solvers, and while the [README](https://github.com/PatWie/CppNumericalSolvers/blob/main/README.md) provides a quick overview and a basic example (like minimizing the Rosenbrock function with BFGS), the most detailed insights into the algorithms come from their original papers. Some relevant papers are linked in [this issue](https://github.com/PatWie/CppNumericalSolvers/issues/100), which might be a great starting point for further reading.

For more advanced or challenging examples, I recommend checking out the unit tests in the repository. They include a variety of use cases and scenarios that showcase the solvers' capabilities.

If you have specific questions or run into any issues, feel free to open a discussion or issue here on GitHub. I’d be happy to help!Thank you for your kind words and interest in this repository!

Closing for now this issue.
