### ISSUE TITLE
Compile error on BfgsSolver<float>

### ISSUE THREAD

**Issue by Daiver** [PatWie/CppNumericalSolvers#15]
I just change type of solver/objFunction/vectors from double to float in linear regression example and recieve several compile errors in files like problem.h/morethuente.h and etc. 
So my question: is CppNumericalSolvers ready for using with float?

Most of these errors connected with constants and fabs calls in std::max/min. If it acceptably i can add (T) casts to constants and replace fabs by std::abs and make pull request (if i will have enough time). 

PS Sorry for my poor English

**Comment by PatWie** [comment]
It should work with any datatype. Probably there are some "static_cast 
<T>(varname)" missing. Would be great if you can resolve this issue.

**Comment by Daiver** [comment]
I added static_cast / std::abs and added copy of rosenbrock example with float type. Everything compiling and optimzation returns nice argument (0.999961 0.999923 by CG solver) but checkGradient fails with message 

    The difference between actual_grad[d] and expected_grad[d] is 662.70254516601562, which exceeds     1e-2 * scale, where
    actual_grad[d] evaluates to 396,
    expected_grad[d] evaluates to -266.70254516601562, and
    1e-2 * scale evaluates to 3.96.

With double everything ok.
I will try  solve this problem again in a few days

**Comment by PatWie** [comment]
There might be some troubles with eps using the float representation. I switched to something relative to `std::numeric_limits<T>::epsilon()`. Though, I saw this change was only in `finiteHessian`.
