### ISSUE TITLE
Compilerflag is missing

### ISSUE THREAD

**Issue by PatWie** [PatWie/CppNumericalSolvers#17]
```
set(CMAKE_BUILD_TYPE Release)
```
would make everything much faster!

**Comment by spinicist** [comment]
Hello,
This line should be removed from CMakeLists.txt. The build type should either be set on the command line with -DCMAKE_BUILD_TYPE=Release or using the ccmake UI. Having this line in CMakeLists.txt over-rides what the user selects in ccmake, which makes the tests impossible to build in Debug or RelWithDebInfo mode.
Thanks,
Toby
