### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by AlexanderFabisch** [PatWie/CppNumericalSolvers#18]
Hi,

I tried to install the library with

    mkdir build
    cmake ..
    cd build
    sudo make install

That does not seem to work correctly. The output is

```
$ sudo make install
...
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/verify
-- Removed runtime path from "/usr/local/bin/verify"
-- Installing: /usr/local/bin/benchmark
-- Removed runtime path from "/usr/local/bin/benchmark"
```

I would expect that the headers will be copied to `/usr/local/include`.

I saw in the CMakeLists.txt that there is a custom target which points to a file `cmake/install.cmake` that does not exist:

    add_custom_target(install COMMAND ${CMAKE_COMMAND} -P ${PROJECT_SOURCE_DIR}/cmake/install.cmake)

I wonder why there is no CMake error though.

**Comment by PatWie** [comment]
mkdir build
        cd build
        cmake ..

Is correct, you need to call *cmake* inside the build-dir.

**Comment by AlexanderFabisch** [comment]
Yes, I did that. I corrected the bug report. But it does not copy the header files to `/usr/local/include`. Apart from that some of the cppoptlib headers use gtest. Is this intended? I have to link the library to compile any code that uses cppoptlib.

**Comment by PatWie** [comment]
Ah. Ok. It is not intended to copy the header files there to usr/include, yet. For other projects simply add the include path to the solver directory.

That cmake-install is definetely a bug. It should not be there. In  general there should not be a dependency to gtest outside the verify.cpp file. I will look at that.

Do not forget to explicitly use the release mode (see other issue).

**Comment by AlexanderFabisch** [comment]
Thanks.

Are there any plans to make it possible to install the library in the system? I think we only would have to

* add something like `install(DIRECTORY include/... DESTINATION include/...)`
* install a config for `find_package` and/or pkg-config like in [this library](https://github.com/AlexanderFabisch/robot_model/blob/indigo-devel/kdl_parser/CMakeLists.txt)
* get rid of the gtest dependency by default

**Comment by PatWie** [comment]
Getting rid of "gtest" is my goal. In my opinion it is not the best solution currently to install it in the system. This would prevent a "git pull" update.

**Comment by AlexanderFabisch** [comment]
Well, that would still be possible. You don't have to call make install.
