### ISSUE TITLE
Possible issue ?

### ISSUE THREAD

**Issue by rperrot** [PatWie/CppNumericalSolvers#21]
Hi, 

first of all, thank you for your library, it's really usefull in C++ context. 

When compiling, I got some warnings and I dont' know if they are important or not : 

The main warning comes from that line : 

https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/linesearch/morethuente.h#L99

I'm wondering if operators are used correctly ? Isn't || instead of | ? Is it the "OR" logical operator or the "OR" binary operator ?

**Comment by PatWie** [comment]
In this case both are equivalent. But I should write || there. 

For critical issues I included the unit test. So I can sleep each night without many worries. What compiler and what plattform you are building this?

**Comment by rperrot** [comment]
MSVC 2015 produces the warnings. (it suggests a strict parenthesis because
of operator precedence)

2016-02-11 17:13 GMT+01:00 Patrick Wieschollek <notifications@github.com>:
