### ISSUE TITLE
feature request: bazel support

### ISSUE THREAD

**Issue by jdc2172** [PatWie/CppNumericalSolvers#23]
Would you consider adding support for google's [bazel](http://bazel.io/) build system? It would make it easier to include this project as a dependency in other bazel projects

**Comment by PatWie** [comment]
Haven't looked into right now and I never used before. Sounds good to me. Do you think you can make a pull-request for including bazel?

**Comment by PatWie** [comment]
Not sure, if it really make sense to include a bazel build just for the tests. Recap this is a header-only library. Currently, cmake does the job as well.

**Comment by PatWie** [comment]
The latest version now uses Bazel!

**Comment by DrRibosome** [comment]
awesome!
