### ISSUE TITLE
Error when accessing history matrix in lbfgsbsolver.h

### ISSUE THREAD

**Issue by hugandr** [PatWie/CppNumericalSolvers#24]
There's a problem in lbfgsbsolver.h which can cause a error.

From line 249:
```c++
if (test > 1e-7 * newY.squaredNorm()) {
    if (k < this->settings_.m) {
          yHistory.conservativeResize(DIM, k + 1);
          sHistory.conservativeResize(DIM, k + 1);
    } else {
          yHistory.leftCols(this->settings_.m - 1) = yHistory.rightCols(this->settings_.m - 1).eval();
          sHistory.leftCols(this->settings_.m - 1) = sHistory.rightCols(this->settings_.m - 1).eval();
    }
```

If the condition is false, i.e. test <= 1e-7 * newY.squaredNorm(), then k is incremented on line 276.
If the condition is true the next time, k has been incremented but the yHistory & sHistory matrix was not resized, that's why I got an error on the line

`yHistory.leftCols(this->settings_.m - 1) = yHistory.rightCols(this->settings_.m - 1).eval();`

since the matrices don't have the given number of columns.

A possible, simple fix would just be:
```c++
 if (yHistory.cols() < this->settings_.m) {
          yHistory.conservativeResize(DIM, yHistory.cols() + 1);
          sHistory.conservativeResize(DIM, sHistory.cols() + 1);
 } 
```

**Comment by PatWie** [comment]
That's seems to be a bug, yes. Will you provide a pull-request?

Just for testing:
Any idea how to test this failure? Do you have a opt-problem that runs into this bug?
It would be nice to have a test catching these bug for a possible future refactoring. I only know objectives these algorithms cannot solve but never experienced this problem.

Anyway, thanks for your issue.

**Comment by hugandr** [comment]
I used a very special function when I run into this problem. Unfortunately, I don't have an analytical expression, nor a simple procedural form for it. But I'll try to come up with a simple opt-problem.

Sorry for the late reply and thank for fixing the bug!
