### ISSUE TITLE
cmake    --help-policy CMP0042

### ISSUE THREAD

**Issue by spinicist** [PatWie/CppNumericalSolvers#26]
Hello,
when trying to build the project on MAC OS X the following warning is generated:
```
CMake Warning (dev):
   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
   set the policy and suppress this warning.

   MACOSX_RPATH is not specified for the following targets:

    gtest

 This warning is for project developers.  Use -Wno-dev to suppress it.
```
To be honest, I don't understand @rpath at the moment, but thought you ought to know about it.

Thanks,
Toby

**Comment by spinicist** [comment]
And when trying to build, it fails with:
Scanning dependencies of target gtest
[ 10%] Building CXX object include/gtest/CMakeFiles/gtest.dir/gtest-all.cpp.o
In file included from /Users/Tobias/Code/CppNumericalSolvers/include/gtest/gtest-all.cpp:39:
/Users/Tobias/Code/CppNumericalSolvers/include/gtest/gtest.h:1561:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^
1 error generated.
make[2]: *** [include/gtest/CMakeFiles/gtest.dir/gtest-all.cpp.o] Error 1
make[1]: *** [include/gtest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2

This looks like an internal problem with gtest, which I am completely unfamiliar with.

Thanks,
Toby

**Comment by spinicist** [comment]
Hello again,
I finally managed to get the tests to compile by inserting `#define GTEST_HAS_TR1_TUPLE 0` before every include of gtest.h. This seems a non-optimal solution.

I'm not familiar with gtest but they seem to have updated to cmake fairly recently. Perhaps CppNumericalSolvers can use gtest as an external dependency configured with cmake?

Thanks.

**Comment by PatWie** [comment]
I will have a look how to add gtest as a git-submodul, such that it is possible to get the latest changes of gtest.

**Comment by spinicist** [comment]
Sounds good. An alternative is to simply list it as an external dependency if people want to build the tests, which cuts down on work for you!

**Comment by PatWie** [comment]
Yeah, using git submodules can provide this too by deciding if you do a `git clone` or `git clone recursive`. I will include this this evening.

**Comment by PatWie** [comment]
I added a new branch `"gtest".` While it works, there is a new issue: The Variable `CXX_COMPILER` cannot be set anymore in the `CMakelists.txt`. I added `compile.sh`.

I think the best way is to have a FLAG which tells CMAKE if it should build the tests or not.

**Comment by spinicist** [comment]
Hi, I finally got round to pulling this today. Some comments:

1 - I don't understand why you want to set the compiler with the CXX_COMPILER variable? I let ccmake detect my system compiler and it worked fine.
2 - Because this library is header-only, what would the point of 'compiling' without the tests be?
3 - I am getting the following warning when compiling:
```[ 88%] Building CXX object src/test/CMakeFiles/benchmark.dir/benchmark.cpp.o
In file included from /Users/Tobias/Code/QUIT/External/CppNumericalSolvers/src/test/benchmark.cpp:6:
/Users/Tobias/Code/QUIT/External/CppNumericalSolvers/src/test/../../include/cppoptlib/problem.h:9:9: warning: 
      'EXPECT_NEAR' macro redefined [-Wmacro-redefined]
#define EXPECT_NEAR(x, y, z)
        ^
/Users/Tobias/Code/QUIT/External/CppNumericalSolvers/src/test/../../gtest/googletest/include/gtest/gtest.h:2043:9: note: 
      previous definition is here
#define EXPECT_NEAR(val1, val2, abs_error)\```

Thanks for looking at this, it's much easier to compile now.

**Comment by PatWie** [comment]
Does you latest commits #34 solve this issue? If, can you close this Issue?

**Comment by spinicist** [comment]
I think this has been closed by the recent commits.
