### ISSUE TITLE
Levenberg-Marquardt

### ISSUE THREAD

**Issue by spinicist** [PatWie/CppNumericalSolvers#30]
Hello,
Are there any plans to add a Levenberg-Marquardt type solver? I see the gradient descent and Newton descent solvers, but no LM solver.
Thanks,
Toby

**Comment by PatWie** [comment]
Levenberg-Marquardt can only be used for problems in the form of curve fitting, right? It seems to be a nice addition. Not sure how long it takes for me to implement it.

**Comment by spinicist** [comment]
My only application at the moment is curve-fitting! I had forgotten that LM is specific to that. It's close to a gold standard in the Physics community.

I currently use the implementation is in Eigen's /unsupported directory, but it would be very convenient to have in CppSolvers next to the others if possible.

**Comment by Daiver** [comment]
@PatWie  what difference between curve fitting and general optimization? 
If i not mistaken LM only requires sum of squares of some functions as objective

**Comment by PatWie** [comment]
Consider `f(x)=-x` in some bounds.

**Comment by spinicist** [comment]
LM requires the residual at each data point, and uses these to build an approximation to the Jacobian matrix (if I remember correctly). It is hence quite different to the single-valued cost functions Solvers that this library currently supports.

**Comment by PatWie** [comment]
Maybe out-of-scope of this lib. But patches adding this feature are welcome.
