### ISSUE TITLE
Base classes should have virtual destructors

### ISSUE THREAD

**Issue by jdumas** [PatWie/CppNumericalSolvers#37]
So that when we extend classes like `ISolver` and `Problem`, we can delete objects from a pointer to their base class.

**Comment by jdumas** [comment]
Also, a bit related, but I think it would be nice the Problem class could have a virtual callback() method, that would be called by all solver after each "main" iteration. This would allow us to dump some info, maybe update an interactive viewer or something.

**Comment by jdumas** [comment]
In meta.h, `std::ostream &operator<<(std::ostream &os, const cppoptlib::Status &s)` should be declared inline (since it's a non-template function defined in a header). Sorry I don't feel like creating a separate issue/pull request for such a minor issue =)

**Comment by PatWie** [comment]
Ah. Thanks for your feedback. I will look into that. Do you think the c++11 lambda as a callback function should be prefered over a virtual function?

**Comment by jdumas** [comment]
I don't see any big trouble with that, a std::function<void(void)> member should be able to encapsulate a pointer to the problem instance. And maybe a reference to the current variable x (to update some viewer for instance). So in that regard, a function pointer is probably more versatile.

**Comment by jdumas** [comment]
Ah, one thing also that would be nice, is that the `callback()` should be able to tell the solver to gracefully stop the optimization. For e.g. if the user press a key to pause/stop the current process, the callback should be able to feedback this information to the solver. I think the easier way to do that is indeed to have a `setCallback()` method in the solver class, and the callback would have a signature `std::function<bool(void)>` for example, returning true iff the termination should be forced.

**Comment by PatWie** [comment]
Can your review my changes in 18b41b165c794b391a75e34d3e416f56cb777d51

This gives me


```
patwie@patwie-Desktop~/CppNumericalSolvers/build (master) $ ./bin/examples/simple_withoptions 
(0001) ||dx||= 400.00000000 	||x||= 9.47114483 	f(x)= 454.8442367601 	 x = [ -9.4704 -0.11838 ]
(0002) ||dx||= 94.70404984 	||x||= 5.09725454 	f(x)= 229.8442637181 	 x = [-4.99827 0.999654 ]
(0003) ||dx||= 199.93077189 	||x||= 4.73393324 	f(x)= 117.3832180024 	 x = [  -4.73356 -0.0591695 ]
(0004) ||dx||= 47.33563447 	||x||= 2.54774508 	f(x)= 61.1721588077 	 x = [-2.49827 0.499654 ]
(0005) ||dx||= 99.93078387 	||x||= 2.36614732 	f(x)= 33.0763576734 	 x = [  -2.36596 -0.0295745 ]
(0006) ||dx||= 23.65962484 	||x||= 1.27343160 	f(x)= 19.0333196540 	 x = [-1.2487 0.24974 ]
(0007) ||dx||= 49.94809689 	||x||= 1.18266415 	f(x)= 12.0142310766 	 x = [  -1.18257 -0.0147821 ]
(0008) ||dx||= 11.82571764 	||x||= 0.63649541 	f(x)= 8.5059015835 	 x = [-0.624135 0.124827 ]
(0009) ||dx||= 24.96540391 	||x||= 0.59112739 	f(x)= 6.7523440244 	 x = [  -0.591081 -0.00738852 ]
(0010) ||dx||= 5.91081214 	||x||= 0.31813755 	f(x)= 5.8758687336 	 x = [ -0.31196 0.0623919 ]
(0011) ||dx||= 12.47838119 	||x||= 0.29546139 	f(x)= 5.4377827799 	 x = [  -0.295438 -0.00369298 ]
(0012) ||dx||= 2.95438309 	||x||= 0.15901371 	f(x)= 5.2188156228 	 x = [-0.155926 0.0311852 ]
(0013) ||dx||= 6.23703096 	||x||= 0.14767956 	f(x)= 5.1093699409 	 x = [  -0.147668 -0.00184585 ]
(0014) ||dx||= 1.47668023 	||x||= 0.07947934 	f(x)= 5.0546660418 	 x = [-0.0779359 0.0155872 ]
(0015) ||dx||= 3.11743603 	||x||= 0.07381422 	f(x)= 5.0273235598 	 x = [  -0.0738085 -0.000922606 ]
(0016) ||dx||= 0.73808454 	||x||= 0.03972591 	f(x)= 5.0136570510 	 x = [-0.0389545 0.00779089 ]
(0017) ||dx||= 1.55817848 	||x||= 0.03689434 	f(x)= 5.0068261619 	 x = [  -0.0368915 -0.000461143 ]
```
