### ISSUE TITLE
Bfgs terminates at nan 

### ISSUE THREAD

**Issue by tosttost** [PatWie/CppNumericalSolvers#4]
The BFGS solver fails to solve the Rosenbrock problem for x0 = (-1.2, 1): it returns (NaN, NaN). This starting point is used in Rosenbrock's paper ( http://comjnl.oxfordjournals.org/content/3/3/175.full.pdf+html ) and makes the optimization more difficult than x0=(1,2) which is proposed in the README. 

I suspect this is caused by the used line search (seems to be the Armijo rule). As far as I know the Armijo rule is not suitable for BFGS because the approximation of the inversed Hessian does not need to stay positive definite. 

Test case:

 auto rosenbrock = [] (const Vector &x) -> double {
        const double t1 = (1-x[0]);
        const double t2 = (x[1]-x[0]*x[0]);
        return   t1*t1 + 100*t2*t2;
    };

    // create derivative of function
    auto Drosenbrock = [] (const Vector x, Vector &grad) -> void {
        grad[0]  = -2*(1-x[0])+200*(x[1]-x[0]*x[0])*(-2*x[0]);
        grad[1]  = 200*(x[1]-x[0]*x[0]);
    };

    // initial guess
    Vector x0(2);x0 << -1.2,1;
    // get derivative
    Vector dx0(2);
    Drosenbrock(x0,dx0);
    // verify gradient by finite differences
    checkGradient(rosenbrock,x0,dx0);

    BfgsSolver g;
    g.solve(x0,rosenbrock,Drosenbrock);

// prints      -nan -nan
    std::cout << std::endl<<std::endl<< x0.transpose();

**Comment by PatWie** [comment]
Good catch! Thanks! I modified the linesearch by a better approximation using the hessian, too. The unit-test starts now in "-1.2,1;". It works :+1:

see 804ebf7b1f2f594066da6ec82858eb6abcac0913

**Comment by tosttost** [comment]
Nice work.

Did you use any literature for that? Your fix destroys the descend property.
For the starting point -1.2, 100 there is an iteration in which the linesearch terminates with f = 110.552, but f_in is only 92.0189.

A few iterations later H is
-0.0470248 0.754048
0.754048 -12.0495
This Matrix is clearly not positive definite and the algorithm terminates with NaN, NaN.

PS a good description of a linesearch algorithm can be found in Rodger Fletcher, Practical Methods of Optimization, Second Edition (the first edition is not very useful). This linesearch is used in the gnu scientific library. I meanwhile wrote my own BFGS solver based on that and atlas - my app is in D and it avoids interfacing to C++...

PPS: H is always symmetric. Your code seems not to use that fact - may Eigens rankUpdate(*) functions for Symmetric/selfadjoint views would improve the performance.

**Comment by PatWie** [comment]
My intension was to use a better approximation (2nd order instead of 1st order) for the line search. Now, I found

 "THE PERFORMANCE OF A MODIFIED ARMIJO LINE SEARCH RULE IN BFGS OPTIMIZATION METHOD" 
(http://www.ccms.or.kr/data/pdfpaper/jcms21_1/21_1_117.pdf)

See "Algorithm 2. Modifed Armijo line search rule". They used the same idea.

Can you upload your line search method (in Dlang) to Github-Gist, so I can look into it?
PS: Feel free to make a pull request or a fork.

**Comment by tesch1** [comment]
I have a frankensteinish branch of this repo with the line search from lbfgs.c patched in (https://github.com/chokkan/liblbfgs) .. it works but it's .. let's say, not the prettiest thing in the world.  I'm not really sure if the same conditions are appropriate for L-BFGS-B linesearch, it seems to stall out sometimes unable to find a suitable interval.  Also appears not to work for newton, haven't looked at why.
In addition, there are wrappers for Ipopt and Hager's ASA_CG (http://users.clas.ufl.edu/hager/papers/Software/)
and the solvers are templated - one of the aims was auto differentiation using dual/hyperduals, or Eigen's autodiff, as of yet unfinished.

**Comment by tosttost** [comment]
"My intension was to use a better approximation (2nd order instead of 1st order) for the line search."
As far as I see neither armijo rule nor your fix does not use any approximation of the function in the search direction to find the stepwidth. You only modified the acceptance criterion based on H. Note that H in BFGS is not the hessian but converges against the inverse of the hessian. The acceptance criterion uses the slope of f in the search direction (and with the fix, H) to ensure sufficient reduction of the function value. This alone is not sufficient for BFGS. 
For BFGS the (strong) Wolfe conditions work well:
1. f(x + t*d) <= f(x) + t*constparam*f'(x)   // satisfied with the armijo rule 
2. |f'(x + t*d)| <= -sigma*f'(x)    // not satisfied with the armijo rule
with
sigma < 1 and f'(*) = d.transpose*grad_f(*)

I do not know about  lbfgs.c linesearch but a the wolfe conditions are mention in the docs, so it probably works.

"THE PERFORMANCE OF A MODIFIED ARMIJO LINE SEARCH RULE IN BFGS OPTIMIZATION METHOD" 
I am not sure that is a good paper. I take a quick look at reference [9] where the new linesearch is presented. BFGS is not mentioned at all and the BFGS would have to work with B=H.inverse() in order to have an approximation of the hessian. This requires to solve a set of linear linear equations (or to invert a matrix) in order to calculate the search direction (and use the BFGS update formula for B).

My implementation of Flechter's linesearch needs a lot of refactoring and it still evaluates the function more often than reported by Fletcher. The algorithm is much longer than the Armijo rule. At the moment it exists only on my disk and needs some work before it can be published on github. I have a lot of other work, so it could take some time. 

May the GSL implementation (written in C) helps - it is based on the same description:
- http://www.gnu.org/software/gsl/
- Download version 1.16 sourcecode 
- the linesearch is the "minimize" function in gsl-1.16/multimin/linear_minimize.c

Pull request / fork: not a real option, because for my purpose it is best to have no C++ code (in special, no C++ templates) at all. Additionally my knowledge of C++ is quite limited - sorry!

**Comment by PatWie** [comment]
It seems to be the way to implement the line search algorithm by Jorge J. More' and David J. Thuente
"Line Search Algorithms with Guaranteed Sufficient Decrease"

@tesch1:
I saw your code. My problem with a templated solvers is a Matlab-binding. It is inappropriate to recompile the source code for each problem statement in Matlab. If there is a solution, I am willing to use templates, too. Hopefully, auto differentiation at compile time. Please drop me an email (base64: cGF0cmlja0B3aWVzY2hvbGxlay5pbmZv), because I am working on a nice, slightly different idea for this project.

In general it would be great to continue this discussion here:
https://groups.google.com/forum/?hl=de#!forum/cppnumericalsolver
