### ISSUE TITLE
Complie Error operator *' : 4 overloads have similar conversions

### ISSUE THREAD

**Issue by iwillburnyou** [PatWie/CppNumericalSolvers#42]
Hello,
Thanks for you solver, really helpful!
I meet a strange error when I use visual studio 2013 64 win10 to complie the project.
The error message is like 
Error   24  error C2666: 'Eigen::MatrixBase<Derived>::operator _' : 4 overloads have similar conversions  
And double click it lead you to neldermeadsolver.h - class NelderMeadSolver  - member function minimize-line 92   const Vector<T> x_r = ((1. + rho)) \* x_bar - (rho)_ x0.col(index[DIM]);

I think Eigen is confused with the template form.However BFGS solver seems to function well which just I plan to use.

**Comment by spinicist** [comment]
Sorry for the slow response. I suspect you may be in a minority using Visual Studio, so you may come across problems that don't exist on other platforms. But - please report them!

Which version of Eigen do you have? Can you build and run the CppNumericalSolver tests (the verify) program on your system?

**Comment by PatWie** [comment]
inactivity --> closed
