### ISSUE TITLE
Lbfgsb still failing with box-constraints (sometimes)

### ISSUE THREAD

**Issue by hugandr** [PatWie/CppNumericalSolvers#49]
Still the same problem as in #32. The same test is still failing:

``` c++
template <class T>
struct LinearFunc : public BoundedProblem<T, 2> {
    using typename Problem<T, 2>::TVector;

    LinearFunc() {
        this->setBoxConstraint(TVector::Zero(), TVector::Ones());
    }

    T value(const TVector& x) {
        return -x[0];
    }
};
TYPED_TEST(LbfgsbTest, LinearFunc)    { SOLVE_PROBLEM(cppoptlib::LbfgsbSolver,LinearFunc, 0.5, 0.5, -1.0) }
```

The minimum should be -1 for x_1=1. However the solver leaves the domain and yields as a result 

```
The difference between -1.0 and f(x) is 45812984490, which exceeds 1e-4, where
-1.0 evaluates to -1,
f(x) evaluates to -45812984491, and
1e-4 evaluates to 0.0001.
```

**Comment by PatWie** [comment]
Ok. But shouldn't be the test:

    TYPED_TEST(LbfgsbTest, LinearFunc)    { SOLVE_PROBLEM(cppoptlib::LbfgsbSolver,LinearFunc, 0.5, 0.5, 0.0) }

since there is the bound at 0?

**Comment by hugandr** [comment]
I think it's correct. I am returning **-**x[0], so the minimum is at x[0]=1 => f(x) = -1

**Comment by PatWie** [comment]
Yeah, your right.

**Comment by PatWie** [comment]
I investigated this issue. The problem is, that there is a NaN value around for your example. 
The paper mention delta_t_min = f' / f''. However, f'' is zero in this case:

https://github.com/PatWie/CppNumericalSolvers/blob/fix49/include/cppoptlib/solver/lbfgsbsolver.h#L86

**Comment by spinicist** [comment]
@PatWie - great work finding this. Does it mean the check for NaN on line 133 should go before line 103?

**Comment by PatWie** [comment]
I am not sure how to fix this exactly. While
https://github.com/PatWie/CppNumericalSolvers/blob/fix49/include/cppoptlib/solver/lbfgsbsolver.h

Solves this instance, it will fail for a Rosenbrock-Float-Version. I will try to understand the original Fortran implementation -- though I never wanted to read this code.

**Comment by spinicist** [comment]
Good luck! I totally understand about not wanting to read Fortran code.

**Comment by yujin-chung** [comment]
I have a problem with Lbfgsb with box-constraints. 

1. The parameter values should be non-negative. If they are negative, the function (loglikelihood) is the negative infinity. I found the gradient "g" computing through finiteGradient() in "problem.h" has "NAN" sometimes, and hence it ended up with parameter values of "NAN". 

2. the values of "xx" in finiteGradient() are not constrained by the lower and upper bounds - probably the computation of gradient is inaccurate. I guess this may be the reason that the value of the objective function (negative loglikelihood) is not alway decreasing.

Could you please advise me with any tips to avoid these problems? Thank you.

**Comment by PatWie** [comment]
I am on holiday, so I give a short reply. The finite difference method is really what it is called. It does not take care of any constraints or bounds. And I think this should be correct.

As pointed out in the readme using finite differences is usually the worst case (in all solvers). Therefore I suggest to use a symbolic derivative or checkout if you can use the autodiff branch.

The NaN problem can be leveraged by using a bigger EPS.

**Comment by PatWie** [comment]
Here are some updates:

In the original code there is something like

```fortran
c           complete updating f1 and f2 while col > 0.
         f1 = f1 + dibp*wmc
         f2 = f2 + 2.0d0*dibp*wmp - dibp2*wmw
      endif

      f2 = max(epsmch*f2_org,f2)
      if (nleft .gt. 0) then
         dtm = -f1/f2
         goto 777
```

So they have a small fix in `f2 = max(epsmch*f2_org,f2)`. However, I did not get into the `f2_org` computations. They did something like
```fortran
      f2 =  -theta*f1 
      f2_org  =  f2
      if (col .gt. 0) then
         call bmv(m,sy,wt,col,p,v,info)
         if (info .ne. 0) return
         f2 = f2 - ddot(col2,v,1,p,1)
      endif
      dtm = -f1/f2
      tsum = zero
      nseg = 1
```
So there seems to be another second derivative. While they safeguard one f1/f2 they did not safeguard the other f1/f2.


So maybe it is really just a quick-fix.

**Comment by faberliu** [comment]
Did this bug get fixed？

**Comment by PatWie** [comment]
The issue remains. 
However, it is not really a bug. It is the algorithm that fails sometimes and/or need a workaround.

**Comment by PatWie** [comment]
A fix would be a workaround. See branch [fix49](https://github.com/PatWie/CppNumericalSolvers/compare/fix49)
