### ISSUE TITLE
cmake improvements

### ISSUE THREAD

**Issue by tamaskenez** [PatWie/CppNumericalSolvers#51]
I've made some cmake improvements, the tests and examples build now, too.
But I'm not able to create a decent PR because of the way Eigen is found:

The current stable Eigen has no config module, the tip has it but only the old-fashioned way of setting EIGEN_\* variables. In my fork I modified Eigen to export a library target `::Eigen3` but it's not an official name.

I modified CppNumericalSolves's CMakeLists to support both `::Eigen3` and your `FindEigen3.cmake`, but it's not elegant. So I'm not going to make a PR but feel free to copy lines from https://github.com/adasworks/CppNumericalSolvers/blob/master/CMakeLists.txt if you find anything you need.

**Comment by PatWie** [comment]
merged in #64
