### ISSUE TITLE
Build Issue -

### ISSUE THREAD

**Issue by SVincelette** [PatWie/CppNumericalSolvers#73]
Hello and thank you for the library,

I am having a build issue on Ubuntu. g++ 4.8 and 5.4. Your help is appreciated. 

In file included from /home/likewise-open/G3TI/scott.vincelette/Projects/TetleyScanner/PBL_1_0/CppNumericalSolvers/src/examples/nonnegls.cpp:4:0:
/home/likewise-open/G3TI/scott.vincelette/Projects/TetleyScanner/PBL_1_0/CppNumericalSolvers/src/examples/../../include/cppoptlib/solver/lbfgsbsolver.h: In member function ‘void cppoptlib::LbfgsbSolver<TProblem>::minimize(TProblem&, typename cppoptlib::LbfgsbSolver<TProblem>::Superclass::TVector&)’:
/home/likewise-open/G3TI/scott.vincelette/Projects/TetleyScanner/PBL_1_0/CppNumericalSolvers/src/examples/../../include/cppoptlib/solver/lbfgsbsolver.h:229:29: error: ‘TVector’ is not a class, namespace, or enumeration
       TVector CauchyPoint = TVector::Zero(DIM);
                             ^
make[2]: *** [src/examples/CMakeFiles/nonnegls.dir/nonnegls.cpp.o] Error 1
make[1]: *** [src/examples/CMakeFiles/nonnegls.dir/all] Error 2
make: *** [all] Error 2

 Best Regards,

Scott V

**Comment by SVincelette** [comment]
Issue Solution for compile-
In all the *solver.h files I had to add a Superclass:: or Super:: (depending what typedef was initially defined) before all TVector::XXX() and THessian::YYY(). 

I would like to understand what I am missing that forces me to do this while it compiles for others. I assume for others the "using typename Super::TVector;" prevents the issue. What pkg/lib/command line option am I missing? 

Thanks for your help.

Best Regards,

Scott

**Comment by spinicist** [comment]
I assume you are compiling with C++11 enabled? That's the only obvious thing I can think of, but you ought to hit a lot more compiler errors if that was switched off.

**Comment by SVincelette** [comment]
Thanks for the response. I do use the c++11 switch.

- Scott

**Comment by spinicist** [comment]
Then unfortunately I am stumped. As you can see here  https://github.com/PatWie/CppNumericalSolvers/blob/master/.travis.yml - we don't specifically test 4.8 and 5.4, but we do test 4.9 and 5 and they pass okay. Are you using CMake or building by hand?

**Comment by SVincelette** [comment]
I am using cmake.

It's not a big issue and you should probably close it. If someone runs into
the same issue at least they have a solution.

Thanks again for the great support and powerful library.

- Scott

On Jan 25, 2017 4:35 PM, "Tobias Wood" <notifications@github.com> wrote:

Then unfortunately I am stumped. As you can see here
https://github.com/PatWie/CppNumericalSolvers/blob/master/.travis.yml - we
don't specifically test 4.8 and 5.4, but we do test 4.9 and 5 and they pass
okay. Are you using CMake or building by hand?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PatWie/CppNumericalSolvers/issues/73#issuecomment-275240150>,
or mute the thread

**Comment by PatWie** [comment]
Doing some matrix-env to test multiple new versions of c++ compilers in Travis-CI is currently pretty annoying because these tests cannot run in a lightweight docker container. From time to time I keep watching if there are some apt-upstreams for latest cmake to allow for these different environments inside docker.

In the near future, there might be also other [interesting compiler errors](https://github.com/PatWie/CppNumericalSolvers/pull/72) because of Eigen.
