### ISSUE TITLE
Tolerance and itermax

### ISSUE THREAD

**Issue by tvatter** [PatWie/CppNumericalSolvers#79]
Hi,

I'm not really sure how to do a feature request, so I'm sorry if opening an issue is not the proper way to do so.

Here it goes: is there a plan to add something like itermax, xabs/xrel and fabs/frel tolerance options in the future?

**Comment by spinicist** [comment]
Hi,
I implemented a criteria struct that does some of this: https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/meta.h#L70

I incorporated this into a couple of the solvers (LBFGS-B in particular), but I didn't get round to doing all of them. If you implement anymore please submit a Pull Request. I'm sure @PatWie would be glad of the help!

**Comment by tvatter** [comment]
Thanks a lot, I will have a look!
