### ISSUE TITLE
LbfgsbSolver not working properly. Always return initial value.

### ISSUE THREAD

**Issue by ElonLiu** [PatWie/CppNumericalSolvers#8]
Use `LbfgsbSolver` to test on Rosenbrock function:

```
void testLBFGSB()
{
    pwie::Vector x(2), lb(2), ub(2);
    x(0) = 0;
    x(1) = 0;
    lb(0) = -2; lb(1) = -2;
    ub(0) = 2; ub(1) = 2;
    pwie::LbfgsbSolver solver;
    solver.setLowerBound(lb);
    solver.setUpperBound(ub);
    solver.solve(x, rosenbrock, Drosenbrock);
    std::cout << "Results: " << x(0) << ' ' << x(1) << std::endl;
}
```

Since the bounds are set to [-2, 2], which cover the global minimum, the solution should still be similar to (1,1). However, the results returned are always the initial values.

**Comment by PatWie** [comment]
The L-BFGS-B is very sensitive to the objective function and initialization of the Rosenbrock function.  I can solve a dual SVM with the implementation. I know that the step-width function is not the best choice yet. Thats on my todo-list.

**Comment by spinicist** [comment]
Have you made any progress on this issue? I am having the exact same problem. Lbfgs does make progress, but Lbfgsb only returns the initial guess.

Interestingly, if I add print statements inside my objective function, I can see that it is evaluating points with a better residual, but doesn't give them back?

**Comment by PatWie** [comment]
There was anther paper about L-BFGS-B I was not aware of. Before making any new commit I have to debug my implementation of the HZ update rule which would find points satisfying both Wolfe-conditions.

**Comment by spinicist** [comment]
Okay - I'm looking forward to trying it when you have finished debugging!

**Comment by PatWie** [comment]
I added the linear search of MoreThuente. However, the refactoring destroyed the L-BFGS-B.

**Comment by PatWie** [comment]
See unittest. Lbfgsb is mow working again
