### ISSUE TITLE
A way to evaluate a set of 'x' ?

### ISSUE THREAD

**Issue by rtrepos** [PatWie/CppNumericalSolvers#84]
Hi, 
Thnaks for this work.
It seems one has to evaluation a 'x' one at a time.

The only function in Problem we have access is :
virtual Scalar value(const TVector &x) = 0;

Could it be possible to allow the evaluation of multiple input combinations ?
Something like:
virtual TVector value(const Matrix &x) = 0;

The reason is that one can performs parallel evaluations of the function. In CMA-ES it seems relevant to use it no ?

**Comment by PatWie** [comment]
You can add 
```
TVector value(const  THession &x){}
```

Maybe a default version of this, can be added to the Problem-Interface. But the only solver which would benefit from this is CMA-ES.

**Comment by rtrepos** [comment]
Thanks for this answer, but i m note sure to understand.
- Why use an hessian as input of value function ? (is it a way to say a matrix ?)
- Once I have added this to my problem instantiation, I still have to modify the code of cma solver in order to use it, isn't it ?

**Comment by PatWie** [comment]
Maybe a renaming of `THessian` is good:
https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/problem.h#L18

Indeed, you need to tell CMAE-ES to use the multi-value evaluation.
