### ISSUE TITLE
compile errors with neldermeadsolver

### ISSUE THREAD

**Issue by iwillburnyou** [PatWie/CppNumericalSolvers#85]
First, thanks for this wonderful lib. Really helpful.
I clone , than run bfgs examples well. Than I change solver to neldermeadsolver, I got lots of compile erros, like:
Error	C2146	syntax error: missing ')' before identifier 'initialSimplexCreated'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	58	
Error	C2065	'not': undeclared identifier	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	58	
Error	C2059	syntax error: ')'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	58	
Error	C2059	syntax error: ';'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	59	
Error	C2065	'Scalar': undeclared identifier	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C2923	'std::vector': 'Scalar' is not a valid template type argument for parameter '_Ty'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C3203	'allocator': unspecialized class template can't be used as a template argument for template parameter '_Alloc', expected a real type	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C2133	'cppoptlib::f': unknown size	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C2512	'std::vector': no appropriate default constructor available	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C3927	'->': trailing return type is not allowed after a non-function declarator	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C3484	syntax error: expected '->' before the return type	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C3613	missing return type after '->' ('int' assumed)	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C2371	'cppoptlib::f': redefinition; different basic types	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C2146	syntax error: missing ';' before identifier 'resize'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	63	
Error	C3927	'->': trailing return type is not allowed after a non-function declarator	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C3484	syntax error: expected '->' before the return type	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C3613	missing return type after '->' ('int' assumed)	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C2371	'cppoptlib::index': redefinition; different basic types	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C2146	syntax error: missing ';' before identifier 'resize'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	64	
Error	C2059	syntax error: 'for'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2143	syntax error: missing ')' before ';'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2143	syntax error: missing ';' before '<'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2059	syntax error: '++'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2059	syntax error: ')'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2143	syntax error: missing ';' before '{'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2447	'{': missing function header (old-style formal list?)	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	65	
Error	C2088	'[': illegal for class	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	70	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	70	
Error	C2440	'initializing': cannot convert from 'cppoptlib::<lambda_7dea42c86a444d2b133737f325cb2fb5>' to 'int'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	70	
Error	C2355	'this': can only be referenced inside non-static member functions or non-static data member initializers	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	73	
Error	C2227	left of '->m_stop' must point to class/struct/union/generic type	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	73	
Error	C2228	left of '.iterations' must have class/struct/union	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	73	
Error	C2065	'DIM': undeclared identifier	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	73	
Error	C2789	'cppoptlib::maxIter': an object of const-qualified type must be initialized	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	73	
Error	C2059	syntax error: 'while'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	74	
Error	C2143	syntax error: missing ';' before '{'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	77	
Error	C2447	'{': missing function header (old-style formal list?)	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	77	
Error	C3927	'->': trailing return type is not allowed after a non-function declarator	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	192	
Error	C3484	syntax error: expected '->' before the return type	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	192	
Error	C3613	missing return type after '->' ('int' assumed)	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	192	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	192	
Error	C2146	syntax error: missing ';' before identifier 'detailed_callback'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	192	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	193	
Error	C2065	'x0': undeclared identifier	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	193	
Error	C2228	left of '.col' must have class/struct/union	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	193	
Error	C2088	'[': illegal for class	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	193	
Error	C2059	syntax error: '}'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	194	
Error	C2143	syntax error: missing ';' before '}'	test_vs2015	d:\dev_lib\new_folder\include\cppoptlib\solver\neldermeadsolver.h	194	

------------------
I work with vs2015 and eigen3.3.3
Wired thing is I run neldermeadsolver well with a very old version of CppNumericalSolvers code.

Best regards

**Comment by PatWie** [comment]
Can you change:
https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/solver/neldermeadsolver.h#L58

the `not` to `!`?

**Comment by iwillburnyou** [comment]
Thanks a lot! I change not with ! (and 'and' with '&&") than it works! Thank you again for you time to answer the primary problem. I really donot catch up with the new c++ feature for a while.
