### ISSUE TITLE
VS10 version

### ISSUE THREAD

**Issue by AlexMorgand** [PatWie/CppNumericalSolvers#87]
Hi !

Thank you for your work on this library. I'm working on a reimplementation of one of my method from matlab to C++ and your library helped me a lot simplified the readability of my code.

I work on VS10 (not supporting C++11 features) and I rewrote parts of your library to make it work.
Do you want me to contribute to your library (create a C++03 branch for instance)?

Cheers,

**Comment by PatWie** [comment]
Nice to hear some feedback. This library is planned for c++11 and I do not plan to use c++03. But you are welcome to create such a branch.
