### ISSUE TITLE
Question: Can I use BoundedProblem with a dynamic dimension?

### ISSUE THREAD

**Issue by RobertLRead** [PatWie/CppNumericalSolvers#88]
I am not a C++ expert.  I've tried to understand  the examples and tests.  I see there is a lot of code for using BoundedProblem (lbfgsbsolver.h), but I am having a hard time picking out a comprehensible example I can follow.

**Comment by PatWie** [comment]
The NNLS example might help:

1. implement objective function and gradients (without box-constraints)
https://github.com/PatWie/CppNumericalSolvers/blob/087300c2561f14b53747cb7df27d204ef24e3b82/src/examples/nonnegls.cpp#L25-L31

2. add box-constraint
https://github.com/PatWie/CppNumericalSolvers/blob/087300c2561f14b53747cb7df27d204ef24e3b82/src/examples/nonnegls.cpp#L51
