### ISSUE TITLE
BoundedProblem and finiteGradient

### ISSUE THREAD

**Issue by tvatter** [PatWie/CppNumericalSolvers#92]
Hi,

I am encountering problems when using BoundedProblem without defining the gradient analytically.

Looking at the code, it seems that the function finiteGradient does not adjust for the case where `xx[d] += coeff2[accuracy][s]*eps;` might result in a value outside the bounds. Am I missing something here?

**Comment by PatWie** [comment]
Yes. The finite gradient computation does not take the constraints into account. Not violating the constraints is the task of the optimizer, not the gradient computation part.
