### ISSUE TITLE
the stop criteria is not implemented correct in lbfgsbsolver?

### ISSUE THREAD

**Issue by CgGraphic** [PatWie/CppNumericalSolvers#98]
I found that the  fDelta and xDelta in lbfgsb is not updated to this->m_current;

**Comment by PatWie** [comment]
The convergence check 
https://github.com/PatWie/CppNumericalSolvers/blob/7b1116ca50912f0d90ac0df957411bf097e43d16/include/cppoptlib/solver/lbfgsbsolver.h#L276-L278

is the same as in 

https://github.com/PatWie/CppNumericalSolvers/blob/7b1116ca50912f0d90ac0df957411bf097e43d16/include/cppoptlib/solver/bfgssolver.h#L55-L57

The `xDelta` is for **non**-gradient-based methods. In other methods, checking the norm of the gradient seems to be a better option. Checking xDelta seems to be redundant from my side.
Feel free to react, when disagreeing.

Closing this issue for now.
