### ISSUE TITLE
Max number of variables

### ISSUE THREAD

**Issue by xsedla0k** [PatWie/CppNumericalSolvers#99]
Hi there, 

I have a question how many variable could be solved with your method(s).

I must optimize objective function with about +10 000 parameters, and i am worrying about low memory error. Thanks for answer. ;)

**Comment by PatWie** [comment]
This obviously depends on your machine and objective function. I guess that for 10000+ parameter you will need some time. 

If the objective function is simply convex I suggest to have a look at simpler algorithm implemented in CUDA. Or relying on TensorFlow or PyTorch only which does all on the GPU (excl. scipy-opt)
